language: java
notifications:
  hipchat:
    rooms:
      secure: UtajWUvNKlUDUDigvKke9GcgYpvNhde0SU+BHkuxsTHdjGnjjBQ7ebhBIe2vziekkivV4LW2DlXQUA84kZCJUKT7xg1dzl8XDIMKCkDLraREvM6X694j7QoiTXxS1e5WOrxefoVNhpnL4ZaABgQIkXXl8M2afvG4lVqVpm5D8AA=
deploy:
  provider: releases
  api_key:
    secure: VCLFgZ77ppDlMEM/Z6KiwG0MsW4SxVBlI3cgTn/L+1F6PWj9J40bT4Gp11ymydiO1P6GdPsBqUcBjo0KbeNmC6DdjEvAoJKrcBEH5w4OB0xk65ckBs4XOh6NLliMHHc9cLgo6nMNaFp04UGfngMxardani/CL4X+Llid04lQJls=
  file: build/distributions/xld-openshift-plugin-6.2.0.xldp
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-openshift-plugin
